FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./apps/web ./apps/web

COPY . .

RUN bun install --verbose
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bunx turbo build --filter=web...

EXPOSE 3000

CMD ["bun","run","start:fe"]

