name: Deploy the Frontend
on:
  push:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name : Build and Push to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.fe
          build-args: 
            - DATABASE_URL: ${{ secrets.DATABASE_URL }}
          push: true
          tags: saumilbisht/project-frontend:${{ github.sha }}

      #Deploy to VM
